development:
  adapter: postgresql
  encoding: unicode
  database: new_task_development
  user: octo
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: new_task_test
  user: octo
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: new_task
  pool: 10
  min_messages: warning
  user: octo
  password: 1234
